Repository openshift/image-registry, pull requests merged in 2018-05, with the labels that each got.

#84 better golang version checking
  hack/lib/build/binaries.sh
Labels: approved, lgtm, size/M

#88 Support TEST_KUBECONFIG for integration tests
  Makefile
  pkg/testframework/master.go
  test/integration/crossmount/crossmount_test.go
  test/integration/offline/offline_test.go
  test/integration/pullthroughblob/pullthroughblob_test.go
Labels: approved, lgtm, size/L

#90 UPSTREAM: docker/distribution: 2599: Fix deadlock in the inmemory storage driver
  vendor/github.com/docker/distribution/registry/storage/driver/inmemory/driver.go
Labels: approved, lgtm, size/XS
