Repository openshift/image-registry, pull requests merged in 2018-03, with the labels that each got.

#72 Improve error handling
  pkg/cmd/dockerregistry/restore.go
  pkg/dockerregistry/server/prune/restore.go
Labels: approved, lgtm, size/S

#65 Remove Tag/Untag
  pkg/dockerregistry/server/blobdescriptorservice_test.go
  pkg/dockerregistry/server/manifestservice.go
  pkg/dockerregistry/server/tagservice.go
  pkg/dockerregistry/server/tagservice_test.go
  pkg/imagestream/imagestream.go
Labels: approved, lgtm, size/L

#73 Use SAR request to verify metrics access
  pkg/dockerregistry/server/app.go
  pkg/dockerregistry/server/auth.go
Labels: approved, lgtm, size/M
