Repository openshift/image-registry, pull requests merged in 2018-07, with the labels that each got.

#109 Fix tests for go1.10
  test/integration/pullthroughblob/pullthroughblob_test.go
Labels: approved, lgtm, size/XS

#110 Logs
  images/dockerregistry/config.yml
  pkg/cmd/dockerregistry/dockerregistry.go
  pkg/dockerregistry/server/app.go
  pkg/dockerregistry/server/manifestservice.go
  pkg/dockerregistry/server/pullthroughblobstore.go
  pkg/dockerregistry/server/pullthroughmanifestservice.go
  pkg/dockerregistry/server/remoteblobgetter.go
  pkg/dockerregistry/server/repository.go
  pkg/dockerregistry/server/tagservice.go
  pkg/dockerregistry/server/token.go
  pkg/errors/errors.go
  pkg/imagestream/cachedimagestreamgetter.go
  pkg/imagestream/image.go
  pkg/imagestream/imagestream.go
  pkg/imagestream/imagestreamhasblob.go
  vendor/github.com/docker/distribution/registry/handlers/app.go
  vendor/github.com/docker/distribution/registry/storage/filereader.go
  vendor/github.com/docker/distribution/registry/storage/filereader_test.go
Labels: approved, lgtm, size/XL

#101 Perform an O(1) check to find layers in an image
  .travis.yml
  hack/lib/constants.sh
  hack/test-local-registry.sh
  pkg/dockerregistry/server/blobdescriptorservice.go
  pkg/dockerregistry/server/client/interfaces.go
  pkg/dockerregistry/server/repository_test.go
  pkg/dockerregistry/server/util.go
  pkg/imagestream/cachedimagestreamgetter.go
  pkg/imagestream/imagestream.go
  pkg/imagestream/imagestreamhasblob.go
  pkg/testutil/fakeopenshift.go
Labels: approved, lgtm, size/L

#111 Add metrics for digest cache
  pkg/dockerregistry/server/app.go
  pkg/dockerregistry/server/cache/blobdescriptor.go
  pkg/dockerregistry/server/cache/blobdescriptor_test.go
  pkg/dockerregistry/server/cache/blobstater.go
  pkg/dockerregistry/server/cache/blobstater_test.go
  pkg/dockerregistry/server/cache/cache.go
  pkg/dockerregistry/server/cache/cache_test.go
  pkg/dockerregistry/server/cache/cacheprovider.go
  pkg/dockerregistry/server/cache/cacheprovider_test.go
  pkg/dockerregistry/server/cache/repodigest.go
  pkg/dockerregistry/server/cache/repodigest_test.go
  pkg/dockerregistry/server/manifestservice_test.go
  pkg/dockerregistry/server/metrics/metrics.go
  pkg/dockerregistry/server/metrics/prometheus.go
  pkg/dockerregistry/server/metrics/testing/counter.go
  pkg/dockerregistry/server/pullthroughblobstore_test.go
  pkg/dockerregistry/server/pullthroughmanifestservice_test.go
  pkg/dockerregistry/server/registry_test.go
  pkg/dockerregistry/server/remoteblobgetter.go
  pkg/dockerregistry/server/repository.go
Labels: approved, lgtm, size/XL
