Repository openshift/image-registry, pull requests merged in 2018-09, with the labels that each got.

#121 README: add registry documentation link.
  README.md
Labels: approved, lgtm, retest-not-required-docs-only, size/XS

#122 clean up owners
  OWNERS
Labels: approved, lgtm, size/XS

#124 Fix manifest deletion
  pkg/dockerregistry/server/auth.go
  pkg/dockerregistry/server/auth_test.go
  pkg/testframework/manifest.go
  pkg/testframework/master.go
  pkg/testframework/registry.go
  test/integration/deletemanifest/deletemanifest_test.go
  test/integration/manifestmigration/manifestmigration_test.go
  test/integration/metricspullthrough/metricspullthrough_test.go
  test/integration/offline/offline_test.go
  test/integration/pullthroughblob/pullthroughblob_test.go
Labels: approved, lgtm, size/L
