Repository openshift/image-registry, pull requests merged in 2018-06, with the labels that each got.

#91 Move version check to warn loglevel
  vendor/github.com/docker/distribution/registry/handlers/app.go
Labels: approved, lgtm, size/XS

#92 UPSTREAM: docker/distribution: 2138: image pull returns 404 on manifest request if there is storage error
  vendor/github.com/docker/distribution/registry/handlers/api_test.go
  vendor/github.com/docker/distribution/registry/handlers/images.go
Labels: approved, lgtm, size/L

#93 Remove remote stat from blobDescriptorService
  pkg/dockerregistry/server/blobdescriptorservice.go
  pkg/dockerregistry/server/context.go
  pkg/dockerregistry/server/pullthroughmanifestservice.go
  pkg/dockerregistry/server/repository.go
Labels: approved, lgtm, size/M

#86 Provide clients with additional information on failures
  pkg/dockerregistry/server/pullthroughmanifestservice.go
  pkg/errors/errors.go
  pkg/errors/handle.go
  vendor/github.com/docker/distribution/registry/api/errcode/errors.go
  vendor/github.com/docker/distribution/registry/handlers/app.go
Labels: approved, lgtm, size/M

#94 UPSTREAM: docker/distribution: 2605: s3: Add eu-west-3 region
  vendor/github.com/docker/distribution/registry/storage/driver/s3-aws/s3.go
Labels: approved, lgtm, size/XS

#98 [3.9] UPSTREAM: docker/distribution: 2605: s3: Add eu-west-3 region
  vendor/github.com/docker/distribution/registry/storage/driver/s3-aws/s3.go
Labels: approved, size/XS

#100 search tag events by tag before searching by age age
  pkg/imagestream/imagestreamhasblob.go
Labels: approved, lgtm, size/S

#105 Return 404 when image stream doesn't exist
  pkg/dockerregistry/server/tagservice.go
  pkg/dockerregistry/server/tagservice_test.go
Labels: approved, lgtm, size/S

#103 pullthrough is not optional
  pkg/dockerregistry/server/blobdescriptorservice.go
  pkg/dockerregistry/server/configuration/configuration.go
  pkg/dockerregistry/server/registry_test.go
  pkg/dockerregistry/server/repository.go
  pkg/dockerregistry/server/repository_test.go
  pkg/dockerregistry/server/tagservice.go
  pkg/dockerregistry/server/tagservice_test.go
  pkg/imagestream/imagestream.go
  pkg/imagestream/imagestreamhasblob.go
Labels: approved, lgtm, size/L

#89 Add metrics for the storage subsystem
  pkg/dockerregistry/server/app.go
  pkg/dockerregistry/server/metrics/metrics.go
  pkg/dockerregistry/server/metrics/prometheus.go
  pkg/dockerregistry/server/metrics/testing/counter.go
  pkg/dockerregistry/server/wrapped/filewriter.go
  pkg/dockerregistry/server/wrapped/readcloser.go
  pkg/dockerregistry/server/wrapped/storagedriver.go
  pkg/dockerregistry/server/wrapped/wrapper.go
  pkg/dockerregistry/server/wrapped/wrapper_test.go
  test/integration/metricspullthrough/metricspullthrough_test.go
Labels: approved, lgtm, size/L

#87 Registry catalog
  pkg/dockerregistry/server/app.go
  pkg/dockerregistry/server/auth.go
  pkg/dockerregistry/server/catalog.go
  pkg/dockerregistry/server/catalog_test.go
  pkg/dockerregistry/server/registry.go
  pkg/dockerregistry/server/registry_test.go
  pkg/testutil/fakeopenshift.go
Labels: approved, lgtm, size/L

#81 Cache provider
  pkg/dockerregistry/server/app.go
  pkg/dockerregistry/server/cache/cacheprovider.go
  pkg/dockerregistry/server/cache/cacheprovider_test.go
  pkg/dockerregistry/server/configuration/configuration.go
  pkg/dockerregistry/server/supermiddleware/app.go
  pkg/dockerregistry/server/supermiddleware/app_test.go
  vendor/github.com/docker/distribution/registry/handlers/app.go
  vendor/github.com/docker/distribution/registry/storage/cache/provider/cacheprovider.go
Labels: approved, lgtm, size/L

#97 Metrics for OpenShift client and HTTP handlers
  pkg/dockerregistry/server/app.go
  pkg/dockerregistry/server/metrics/prometheus.go
  pkg/kubernetes-common/README.md
  pkg/kubernetes-common/prometheus/prometheus.go
Labels: approved, lgtm, size/L
