Repository openshift/image-registry, pull requests merged in 2019-02, with the labels that each got.

#155 Remove legacy path from imageStream.HasBlob
  pkg/dockerregistry/server/blobdescriptorservice_test.go
  pkg/dockerregistry/server/catalog.go
  pkg/dockerregistry/server/manifestservice.go
  pkg/dockerregistry/server/manifestservice_test.go
  pkg/dockerregistry/server/repository_test.go
  pkg/dockerregistry/server/util.go
  pkg/imagestream/imagestream.go
  pkg/imagestream/imagestreamhasblob.go
  pkg/testutil/fakeopenshift.go
  test/integration/manifestmigration/manifestmigration_test.go
Labels: approved, lgtm, size/XL

#157 Clean owners
  cmd/dockerregistry/OWNERS
  pkg/dockerregistry/OWNERS
  tools/OWNERS
Labels: approved, lgtm, retest-not-required, size/XS

#161 [3.11] prevent external hostname pullthrough + bump digest cache size
  pkg/dockerregistry/server/app.go
  pkg/imagestream/identifycandidaterepositories.go
  pkg/imagestream/identifycandidaterepositories_test.go
  pkg/imagestream/imagestream.go
Labels: approved, lgtm, size/M

#158 Add request tracer to avoid loops
  pkg/dockerregistry/server/pullthroughblobstore_test.go
  pkg/dockerregistry/server/pullthroughmanifestservice.go
  pkg/dockerregistry/server/pullthroughmanifestservice_test.go
  pkg/dockerregistry/server/remoteblobgetter.go
  pkg/dockerregistry/server/repository_test.go
  pkg/dockerregistry/server/util.go
  pkg/origin-common/image/registryclient/client.go
  pkg/requesttrace/requesttrace.go
  pkg/requesttrace/requesttrace_test.go
  pkg/testframework/registry.go
  test/integration/requestloop/requestloop_test.go
Labels: approved, lgtm, size/L

#163 prevent external hostname pullthrough + bump digest cache size
  pkg/dockerregistry/server/app.go
  pkg/imagestream/identifycandidaterepositories.go
  pkg/imagestream/identifycandidaterepositories_test.go
  pkg/imagestream/imagestream.go
Labels: approved, lgtm, size/M

#164 [3.11] Add request tracer to avoid loops
  pkg/dockerregistry/server/pullthroughblobstore_test.go
  pkg/dockerregistry/server/pullthroughmanifestservice.go
  pkg/dockerregistry/server/pullthroughmanifestservice_test.go
  pkg/dockerregistry/server/remoteblobgetter.go
  pkg/dockerregistry/server/repository_test.go
  pkg/dockerregistry/server/util.go
  pkg/origin-common/image/registryclient/client.go
  pkg/requesttrace/requesttrace.go
  pkg/requesttrace/requesttrace_test.go
  pkg/testframework/registry.go
  test/integration/requestloop/requestloop_test.go
Labels: approved, lgtm, size/L

#167 Bug 1655641: fix S3 health check when Bucket is empty
  glide.lock
  vendor/github.com/docker/distribution/registry/handlers/app.go
  vendor/github.com/pkg/profile/.travis.yml
Labels: approved, lgtm, size/S
