Repository openshift/image-registry, pull requests merged in 2019-08, with the labels that each got.

#184 Introduce gosec for security checks
  Makefile
  pkg/testframework/httptest.go
  pkg/testframework/master.go
  pkg/testframework/net.go
  pkg/testutil/util.go
  tools/import-verifier/import-verifier.go
Labels: approved, lgtm, size/S

#187 Bug 1739724: Update make verify
  .travis.yml
  Makefile
  hack/verify-golint.sh
  hack/verify-govet.sh
  test/integration/pullthroughblob/pullthroughblob_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#189 Bug 1740391: Update make verify for release-4.1
  Makefile
  hack/verify-govet.sh
  test/integration/pullthroughblob/pullthroughblob_test.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/S

#192 Bug 1710502: Implementing graceful shutdown.
  pkg/cmd/dockerregistry/dockerregistry.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M
