Repository openshift/image-registry, pull requests merged in 2020-02, with the labels that each got.

#220 Bug 1745743: Implement retries when checking for blob presence.
  pkg/dockerregistry/server/manifesthandler/manifestschema1handler.go
  pkg/dockerregistry/server/manifesthandler/manifestschema2handler.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#221 Dockerfile: Clear yum cache after install
  Dockerfile
  Dockerfile.rhel7
Labels: approved, lgtm, size/XS

#224 Remove unused package dockercredentials
  pkg/origin-common/image/registryclient/dockercredentials/credentials.go
  pkg/origin-common/image/registryclient/dockercredentials/credentials_test.go
Labels: approved, lgtm, size/L
