Repository openshift/image-registry, pull requests merged in 2020-04, with the labels that each got.

#233 bump openshift/docker-distribution
  go.mod
  go.sum
  vendor/github.com/docker/distribution/registry/storage/driver/gcs/gcs.go
  vendor/github.com/docker/distribution/registry/storage/driver/s3-aws/s3.go
  vendor/modules.txt
Labels: approved, lgtm

#232 Add component to OWNERS
  OWNERS
Labels: approved, lgtm

#235 Bug 1804160: Permission denied if namespace does not exist
  pkg/imagestream/imagestream.go
  test/integration/uploadblob/uploadblob_test.go
Labels: approved, bugzilla/medium, bugzilla/valid-bug, lgtm

#236 Bug 1827672: Only warn if PublicDockerImageRepository is set
  pkg/imagestream/imagestream.go
Labels: approved, bugzilla/low, bugzilla/valid-bug, lgtm

#237 [release-3.11] Bug 1827744: Reduce cardinality of metrics, use summary instead of histograms
  pkg/dockerregistry/server/metrics/metrics.go
  pkg/dockerregistry/server/metrics/prometheus.go
  pkg/dockerregistry/server/metrics/testing/counter.go
  test/integration/metricspullthrough/metricspullthrough_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm
