Repository openshift/image-registry, pull requests merged in 2022-03, with the labels that each got.

#313 Bug 1976782: Fix s3 driver for supporting ceph radosgw
  go.mod
  go.sum
  vendor/github.com/docker/distribution/registry/storage/driver/s3-aws/s3.go
  vendor/modules.txt
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#315 Bug 2060605: Revert "Fixed incorrect access denied error logs"
  pkg/dockerregistry/server/auth.go
  pkg/dockerregistry/server/auth_test.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-urgent

#318 Bug 2061785: Fix ICSP for subrepositories
  pkg/dockerregistry/server/simplelookupicsp.go
  pkg/dockerregistry/server/simplelookupicsp_test.go
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high, qe-approved, backport-risk-assessed

#320 Bug 2065689: Revert "Support authentication using gcp workload identity federation"
  go.mod
  go.sum
  vendor/github.com/docker/distribution/registry/storage/driver/gcs/gcs.go
  vendor/github.com/docker/distribution/vendor.conf
  vendor/modules.txt
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-urgent

#321 Bug 2069807: Bug 2060362: Revert "Support authentication using gcp workload identity federation"
  go.mod
  go.sum
  vendor/github.com/docker/distribution/registry/storage/driver/gcs/gcs.go
  vendor/github.com/docker/distribution/registry/storage/driver/s3-aws/s3.go
  vendor/github.com/docker/distribution/vendor.conf
  vendor/modules.txt
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-urgent, backport-risk-assessed
