Repository openshift/image-registry, pull requests merged in 2022-05, with the labels that each got.

#327 Bug 2060363: Fix s3 driver for supporting ceph radosgw
  go.mod
  go.sum
  vendor/github.com/docker/distribution/registry/storage/driver/s3-aws/s3.go
  vendor/modules.txt
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-medium, qe-approved, backport-risk-assessed

#329 Bug 1923536: forward http.StatusTooManyRequests to client
  pkg/dockerregistry/server/pullthroughblobstore.go
  pkg/dockerregistry/server/pullthroughmanifestservice.go
  pkg/dockerregistry/server/remoteblobgetter.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high, qe-approved

#331 Bug 2067893: apply upstream prometheus/client_golang fix
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_client.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/option.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium
